### ISSUE TITLE
DB Selection 

### ISSUE THREAD

**Issue by NubeDev** [DieselFuel147/beebit-web#15]
Not an issue at all but FYI for next time!
Last time i looked SQLite is not an encrypted database or `Data at rest` but i may be wrong fell free to correct me :)
https://en.wikipedia.org/wiki/Data_at_rest

**Comment by winzlebee** [comment]
Yep you're right, SQLite is definitely not inherently encrypted :)
There's always the [SEE extension](https://www.hwaci.com/sw/sqlite/see.html) for that, but if we were scaling I guess in that case it would make more sense to have a bigger/remote database infrastructure.
SQLite is a `Data at rest` database to my understanding of the term (it persists database changes between restarts of the runtime), however it doesn't encrypt the data at rest (which would be more ideal). 
Really enjoying the questions! I think next time we will use a more robust database solution, maybe sensible use of an ORM so it's easier on us during development.
